'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,Footprints,Clock,MapPin,ArrowUpRight,Info,Check,RefreshCw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect} from '@/components/ui/native-select';
import buildings from '@/data/buildings.json';
import spaces from '@/data/spaces.json';
import classes from '@/data/classes.json';
import hours from '@/data/hours.json';
import {recommend,forecast,clock,minutes,eastern,freshReports,type Plan,type Report,type Data} from '@/lib/planner';
const data:Data={buildings,spaces,classes,hours};
const example:Plan={from:'NCB',to:'DERR',date:'2026-09-21',start:'09:55',end:'11:15',intent:'study',maxWalk:12,buffer:5,confirmedOnly:false};
const reportLabels={plenty:'Plenty of seats',few:'A few seats',none:'No seats seen'};
export default function Home(){
 const [draft,setDraft]=useState<Plan>(example),[plan,setPlan]=useState<Plan>(example);
 const [reports,setReports]=useState<Report[]>([]),[reportStatus,setReportStatus]=useState('Loading recent reports…'),[now,setNow]=useState(0),[selected,setSelected]=useState(''),[backup,setBackup]=useState(''),[reportSpace,setReportSpace]=useState(spaces[0].id),[posting,setPosting]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const result=useMemo(()=>recommend(plan,data,reports,now),[plan,reports,now]);
 const active=result.results.find(s=>s.id===selected)||result.results[0];
 async function refresh(){try{const r=await fetch('/api/reports');if(!r.ok)throw Error();const x=await r.json() as {reports:Report[]};setReports(x.reports);setReportStatus(x.reports.length?`${x.reports.length} recent student report${x.reports.length===1?'':'s'}`:'No recent reports yet');}catch{setReportStatus('Reports unavailable · forecasts still work');}}
 useEffect(()=>{setNow(Date.now());void refresh();const t=setInterval(()=>{setNow(Date.now());void refresh();},60000);return ()=>clearInterval(t);},[]);
 function apply(p:Plan){const r=recommend(p,data,reports,Date.now());if(r.error){setError(r.error);return;}setError('');setPlan(p);setSelected('');setBackup('');}
 function useNow(){const n=eastern(Date.now());const end=Math.min(n.minute+80,1439);const hh=(m:number)=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;const value={...draft,date:n.date,start:hh(n.minute),end:hh(end)};setDraft(value);apply(value);}
 async function report(level:Report['level']){setPosting(true);setMessage('');try{const r=await fetch('/api/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({spaceId:reportSpace,level})});const body=await r.json() as {error?:string};if(!r.ok)throw Error(body.error||'Could not save your report.');setMessage('Thanks — your observation is saved and visible for 15 minutes.');setNow(Date.now());await refresh();}catch(e){setMessage(e instanceof Error?e.message:'Could not save your report.');}finally{setPosting(false);}}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'configure_gap_plan',description:'Update the visible campus gap plan. Does not reserve seating.',inputSchema:{type:'object',properties:{from:{type:'string'},to:{type:'string'},date:{type:'string'},start:{type:'string'},end:{type:'string'},intent:{type:'string',enum:['study','quiet','group','break']}},required:['from','to','date','start','end','intent'],additionalProperties:false},execute(input:unknown){if(!input||typeof input!=='object')throw Error('Expected plan inputs');const p={...example,...input} as Plan;const r=recommend(p,data);if(r.error)throw Error(r.error);setDraft(p);setPlan(p);setSelected('');setBackup('');setError('');return {status:'configured',places:r.results.map(x=>({name:x.name,usableMinutes:x.usable,leaveBy:clock(x.leave)}))};}},{signal:lifecycle.signal})).catch(()=>{});return ()=>lifecycle.abort();},[]);
 return <><header className="topbar"><a className="wordmark" href="/"><span className="logo">h<span>g</span></span>hokiegap<span className="beta">PROTOTYPE</span></a><span className="campus-label"><MapPin size={15}/> Virginia Tech · engineering cluster</span><a href="#data-notes" className="source-link">About the data <ArrowUpRight size={15}/></a></header>
 <main><section className="intro"><div><p className="eyebrow">BETWEEN CLASSES, ON YOUR TERMS</p><h1>A little gap. A good place.</h1><p>Find somewhere to settle in, with time to make your next class.</p></div><div className="gap-number"><strong>{minutes(plan.end)-minutes(plan.start)}</strong><span>minutes to work with</span></div></section>
 <div className="workspace"><aside className="planner"><div className="panel-title"><span className="step">01</span><h2>Your gap</h2></div><form onSubmit={e=>{e.preventDefault();apply(draft);}}>
 <label>Starting from<NativeSelect value={draft.from} onChange={e=>setDraft({...draft,from:e.target.value})}>{buildings.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</NativeSelect></label>
 <label>Next class in<NativeSelect value={draft.to} onChange={e=>setDraft({...draft,to:e.target.value})}>{buildings.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</NativeSelect></label>
 <label>Date<Input type="date" required min="2026-01-01" max="2026-12-31" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label>
 <div className="two-fields"><label>Free from<Input type="time" required value={draft.start} onChange={e=>setDraft({...draft,start:e.target.value})}/></label><label>Next class<Input type="time" required value={draft.end} onChange={e=>setDraft({...draft,end:e.target.value})}/></label></div>
 <label>I want to<NativeSelect value={draft.intent} onChange={e=>setDraft({...draft,intent:e.target.value})}><option value="study">Get some work done</option><option value="quiet">Find a quieter spot</option><option value="group">Work with friends</option><option value="break">Take a break</option></NativeSelect></label>
 <div className="two-fields"><label>Max walk / leg<NativeSelect value={draft.maxWalk} onChange={e=>setDraft({...draft,maxWalk:+e.target.value})}>{[3,5,8,12,15,20].map(n=><option key={n} value={n}>{n} min</option>)}</NativeSelect></label><label>Arrive early<NativeSelect value={draft.buffer} onChange={e=>setDraft({...draft,buffer:+e.target.value})}>{[0,5,10,15].map(n=><option key={n} value={n}>{n} min</option>)}</NativeSelect></label></div>
 <label>Access<NativeSelect value={draft.confirmedOnly?'confirmed':'all'} onChange={e=>setDraft({...draft,confirmedOnly:e.target.value==='confirmed'})}><option value="all">Include unverified hours</option><option value="confirmed">Published open hours only</option></NativeSelect></label>
 {error&&<p role="alert" className="error">{error}</p>}<Button type="submit" className="primary-btn">Find my spot <ArrowRight size={18}/></Button></form><div className="quick-actions"><Button variant="ghost" onClick={useNow}>Use current time</Button><Button variant="ghost" onClick={()=>{setDraft(example);apply(example);}}>ECE example</Button></div><p className="caption">Example: Monday, Sept 21 · 9:55–11:15.<br/>All times are Eastern.</p></aside>
 <section className="results"><div className="results-heading"><div className="panel-title"><span className="step">02</span><h2>Places that fit</h2></div><span>{result.results.length} {result.results.length===1?"option":"options"}</span></div><p className="results-sub">Sorted by usable time, expected surges and fresh seat reports.</p>
 <div className="report-strip"><span className="status-dot"/>{reportStatus}<Button variant="ghost" size="icon-sm" aria-label="Refresh seating reports" onClick={()=>void refresh()}><RefreshCw size={14}/></Button></div>
 {result.results.length===0&&<div className="empty"><h3>No spots fit this gap yet.</h3><p>Try a longer gap, a larger walking limit or include unverified hours. We require at least 15 usable minutes.</p></div>}
 {result.results.map((s,i)=><article className={`spot-card ${active?.id===s.id?'selected':''}`} key={s.id}><div className="card-kicker"><span>{i===0?'BEST FIT':`OPTION 0${i+1}`}</span><span className={`surge ${s.crowd.label==='Higher surge'?'high':''}`}>{s.crowd.label}</span></div><button className="spot-title" onClick={()=>{setSelected(s.id);if(window.innerWidth<=1120)document.getElementById("route-plan")?.scrollIntoView({behavior:"smooth",block:"start"});}} aria-expanded={active?.id===s.id}>{s.name}<ArrowUpRight size={20}/></button><p className="location">{s.location}</p><div className="metrics"><strong>{s.usable}<small> min here</small></strong><span><Footprints size={16}/>{s.walkIn} min there</span><span><Clock size={15}/>Leave {clock(s.leave)}</span></div><div className="card-bottom"><span className={s.latest?'seat-report':'unknown'}>{s.latest?reportLabels[s.latest.level]+' · student report':'Seats unknown'}</span><span>{s.open?'Published open hours':'Check access hours'}</span></div><div className="card-actions"><Button variant="ghost" onClick={()=>{setSelected(s.id);if(window.innerWidth<=1120)document.getElementById("route-plan")?.scrollIntoView({behavior:"smooth",block:"start"});}}>View plan <ArrowRight size={15}/></Button><Button variant="ghost" disabled={backup===s.id} onClick={()=>setBackup(s.id)}>{backup===s.id?<><Check size={15}/>Backup selected</>:'Keep as backup'}</Button></div></article>)}
 </section>
 <aside id="route-plan" className="detail-panel">{active&&<><div className="panel-title"><span className="step">03</span><h2>Your route & timing</h2></div><div className="mini-map"><svg viewBox="0 0 330 210" role="img" aria-label="Approximate building locations; dotted line is not a walking route"><defs><pattern id="grid" width="22" height="22" patternUnits="userSpaceOnUse"><path d="M 22 0 L 0 0 0 22" fill="none" stroke="#e1ded4" strokeWidth=".6"/></pattern></defs><rect width="330" height="210" fill="url(#grid)"/>{(()=>{const point=(id:string)=>{const b=buildings.find(b=>b.id===id)!;return {x:32+(b.lon+80.427)*33500,y:180-(b.lat-37.2287)*43000};};const points=[plan.from,active.buildingId,plan.to].map(point);return <><polyline points={points.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#861f41" strokeWidth="2" strokeDasharray="5 4"/>{buildings.map(b=>{const p=point(b.id);return <g key={b.id}><circle cx={p.x} cy={p.y} r={b.id===active.buildingId?7:4} fill={b.id===active.buildingId?'#861f41':'#868c7e'}/><text textAnchor={b.id==="NEWMAN"?"end":"start"} x={b.id==="NEWMAN"?p.x-8:p.x+8} y={p.y-7} fontSize="10" fill="#41453e">{b.id}</text></g>;})}</>;})()}<text x="306" y="20" fontSize="10">N ↑</text></svg><span>Approximate locations · not navigation</span></div>
 <h3 className="detail-name">{active.name}</h3><ol className="timeline"><li><span>{clock(minutes(plan.start))}</span><div>Leave {buildings.find(b=>b.id===plan.from)?.name}<small>About {active.walkIn} min to your spot</small></div></li><li className="main-stop"><span>{clock(active.arrival)}</span><div>Settle in for {active.usable} minutes<small>{plan.intent==='break'?'Time to take a breather.':'A pocket of time to make progress.'}</small></div></li><li><span>{clock(active.leave)}</span><div>Head to {buildings.find(b=>b.id===plan.to)?.name}<small>About {active.walkOut} min walking · {plan.buffer} min buffer</small></div></li><li><span>{clock(minutes(plan.end))}</span><div>Next class starts</div></li></ol>
 <div className="forecast"><div><h3>Class-change outlook</h3><span className="small-tag">ESTIMATE</span></div><p>{active.crowd.label} around {clock(active.crowd.time)}</p>{active.crowd.available&&<div className="bars">{Array.from({length:7},(_,i)=>{const t=Math.round(active.arrival+i*(active.leave-active.arrival)/6),c=forecast(active.buildingId,plan.date,t,data);return <div key={i} title={`${clock(t)}: ${c.label}`}><span style={{height:`${Math.max(6,Math.min(58,c.score))}px`,background:c.score>=30?'#ce6a39':c.score>=10?'#d8ad72':'#9aab90'}}/><small>{i%3===0?clock(t).replace(' AM','').replace(' PM',''):''}</small></div>;})}</div>}<p className="caption">Class size and timing suggest pressure on nearby seating. This is an untested estimate, not a seat count.</p>{active.crowd.events.map(e=><p className="event" key={e.room+e.end}>{e.course} ends {clock(e.end)} · {e.room}<small>Section capacity {e.capacity}; enrollment unknown</small></p>)}</div>
 {backup&&<div className="backup"><Check size={16}/><span>Backup for this plan<strong>{spaces.find(s=>s.id===backup)?.name}</strong></span></div>}
 <details className="place-details"><summary>What we know about this spot</summary><p>{active.note}</p><p>{active.verification}. Seat count and current outlet availability are unknown.</p><a href={active.source} target="_blank" rel="noreferrer">Read the place source <ArrowUpRight size={14}/></a><p className="caption">Walks use building coordinates, a 35% detour allowance, 70 m/min pace and 2 minutes indoors. Actual routes, stairs and accessible entrances may take longer.</p></details></>}</aside></div>
 <section className="community"><div><p className="eyebrow">HELP THE NEXT STUDENT</p><h2>Here right now? Share the seat situation.</h2><p>Report only what you can see at the selected spot. Reports are shown for 15 minutes. Anonymous observations may be kept to improve the forecast.</p><p className="caption">Reports describe now, even when your plan is for another day. They influence a plan only if still fresh at arrival.</p></div><div className="report-controls"><label>Where are you?<NativeSelect value={reportSpace} onChange={e=>setReportSpace(e.target.value)}>{spaces.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</NativeSelect></label><div className="report-buttons">{(['plenty','few','none'] as const).map(level=><Button key={level} variant="outline" disabled={posting} onClick={()=>void report(level)}>{reportLabels[level]}</Button>)}</div><p role="status">{message}</p>{freshReports(reports,reportSpace,now)[0]&&<p className="caption">Latest observation: {reportLabels[freshReports(reports,reportSpace,now)[0].level]} · {Math.floor((now-freshReports(reports,reportSpace,now)[0].createdAt)/60000)} min ago</p>}</div></section>
 <details id="data-notes" className="data-notes"><summary><Info size={17}/> Data, coverage & limitations</summary><div className="notes-grid"><div><h3>Real sources, limited coverage</h3><p>Seven building coordinates from VT GIS; seven places from university or architect descriptions. Bishop-Favrao is a start/destination only: a suitable study space is not yet verified.</p><p>The Sept 19 snapshot includes {classes.length} meetings from 14 subjects. Coverage is partial and uses capacity rather than enrollment. No private rosters are collected.</p><a href="https://selfservice.banner.vt.edu/ssb/HZSKVTSC.P_DispRequest" target="_blank" rel="noreferrer">VT public timetable ↗</a></div><div><h3>Forecast, not trained ML</h3><p>The class-change forecast is limited to Sept 19–25, 2026. Outside that week it is unavailable. We assume a small fraction of class capacity lingers after class; these assumptions need observation and calibration.</p><p>Library hours are a dated calendar snapshot. Other opening hours are unknown. Schedules and access can change.</p><a href="https://lib.vt.edu/about-us/hours.html" target="_blank" rel="noreferrer">Check current library hours ↗</a></div><div><h3>No invented live data</h3><p>There are no seeded seating reports. Observations are stored on the service and expire from recommendations after 15 minutes. They are not reservations or guarantees.</p><p>Gemini, Databricks and HokieAI are not connected in this version. This independent student prototype is not an official VT service.</p></div></div></details>
 <footer><span className="wordmark">hokiegap<span className="beta">VT HACKS 14</span></span><span>A better use of the time between.</span></footer></main></>;
}
