'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,Footprints,Clock,MapPin,ArrowUpRight,Info,Check,RefreshCw,Navigation} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect} from '@/components/ui/native-select';
import buildings from '@/data/buildings.json';
import spaces from '@/data/spaces.json';
import classes from '@/data/classes.json';
import hours from '@/data/hours.json';
import {recommend,forecast,clock,minutes,eastern,freshReports,validate,type Plan,type Report,type Data} from '@/lib/planner';
const data:Data={buildings,spaces,classes,hours};
const bootstrapPlan:Plan={from:'NCB',to:'DERR',date:'2026-09-19',start:'12:00',end:'13:00',intent:'study',maxWalk:12,buffer:5,confirmedOnly:false};
const timeValue=(m:number)=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
function currentPlan(base:Plan=bootstrapPlan){const n=eastern(Date.now()),end=Math.min(n.minute+60,1439);return {...base,date:n.date,start:timeValue(n.minute),end:timeValue(end)};}
const reportLabels={plenty:'Plenty of seats',few:'A few seats',none:'No seats seen'};
export default function Home(){
 const [draft,setDraft]=useState<Plan>(bootstrapPlan),[plan,setPlan]=useState<Plan>(bootstrapPlan);
 const [reports,setReports]=useState<Report[]>([]),[reportStatus,setReportStatus]=useState('Loading recent reports…'),[now,setNow]=useState(0),[selected,setSelected]=useState(''),[backup,setBackup]=useState(''),[reportSpace,setReportSpace]=useState(spaces[0].id),[posting,setPosting]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[routeMessage,setRouteMessage]=useState('');
 const [ready,setReady]=useState(false),[favorites,setFavorites]=useState<string[]>([]),[savedGaps,setSavedGaps]=useState<{name:string;plan:Plan}[]>([]),[gapName,setGapName]=useState(''),[showAll,setShowAll]=useState(false),[aiRequest,setAiRequest]=useState(''),[aiBusy,setAiBusy]=useState(false),[aiResult,setAiResult]=useState<any>(null),[aiError,setAiError]=useState(''),[aiEnabled,setAiEnabled]=useState(false);
 const dirty=JSON.stringify(draft)!==JSON.stringify(plan);
 const liveTime=eastern(now||Date.now());
 const departed=plan.date<liveTime.date||(plan.date===liveTime.date&&minutes(plan.start)<liveTime.minute);
 function remember(key:string,value:unknown){try{localStorage.setItem(key,JSON.stringify(value));}catch{}}
 function saveGap(){if(!gapName.trim()||validate(draft,buildings))return;setSavedGaps(v=>[...v.filter(x=>x.name!==gapName.trim()),{name:gapName.trim().slice(0,60),plan:draft}].slice(-8));setGapName('');}
 async function askAgent(){setAiBusy(true);setAiError('');setAiResult(null);try{const r=await fetch('/api/agent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request:aiRequest,plan:draft})});const x=await r.json() as any;if(!r.ok)throw Error(x.error||'Could not create an AI plan.');setDraft(x.plan);setPlan(x.plan);setSelected(x.selectedId||'');setBackup('');setAiResult(x);}catch(e){setAiError(e instanceof Error?e.message:'AI unavailable');}finally{setAiBusy(false);}}

 const result=useMemo(()=>recommend(plan,data,reports,now),[plan,reports,now]);
 const active=result.results.find(s=>s.id===selected)||result.results[0];
 async function refresh(){try{const r=await fetch('/api/reports');if(!r.ok)throw Error();const x=await r.json() as {reports:Report[]};setReports(x.reports);setReportStatus(x.reports.length?`${x.reports.length} recent student report${x.reports.length===1?'':'s'}`:'No recent reports yet');}catch{setReportStatus('Reports unavailable · forecasts still work');}}
 useEffect(()=>{let live=currentPlan();try{const pref=JSON.parse(localStorage.getItem('hg-preferences')||'null');if(pref){const test={...live,...pref,date:live.date,start:live.start,end:live.end};if(!validate(test,buildings))live=test;}const fav=JSON.parse(localStorage.getItem('hg-favorites')||'[]');if(Array.isArray(fav))setFavorites(fav.filter(id=>spaces.some(s=>s.id===id)));const gaps=JSON.parse(localStorage.getItem('hg-gaps')||'[]');if(Array.isArray(gaps))setSavedGaps(gaps.filter(g=>typeof g.name==='string'&&g.plan&&!validate(g.plan,buildings)).slice(-8));const session=JSON.parse(localStorage.getItem('hg-active')||'null');const n=eastern(Date.now());if(session?.plan&&!validate(session.plan,buildings)&&session.plan.date===n.date&&minutes(session.plan.end)>n.minute){live=session.plan;setSelected(session.selected||'');setBackup(session.backup||'');}}catch{}setDraft(live);setPlan(live);setNow(Date.now());setReady(true);void refresh();void fetch('/api/agent').then(r=>r.json()).then((x:any)=>setAiEnabled(x.enabled===true)).catch(()=>{});const t=setInterval(()=>{setNow(Date.now());void refresh();},60000);return ()=>clearInterval(t);},[]);
 useEffect(()=>{if(!ready)return;const {from,to,intent,maxWalk,buffer,confirmedOnly}=plan;remember('hg-preferences',{from,to,intent,maxWalk,buffer,confirmedOnly});remember('hg-active',{plan,selected,backup});remember('hg-favorites',favorites);remember('hg-gaps',savedGaps);},[ready,plan,selected,backup,favorites,savedGaps]);
 function apply(p:Plan){const r=recommend(p,data,reports,Date.now());if(r.error){setError(r.error);return;}setError('');setPlan(p);setSelected('');setBackup('');setAiResult(null);setRouteMessage('');}
 function showPlan(id:string,name:string){setSelected(id);setRouteMessage(`Route updated for ${name}.`);requestAnimationFrame(()=>{const panel=document.getElementById('route-plan');panel?.focus({preventScroll:window.innerWidth>1120});if(window.innerWidth<=1120)panel?.scrollIntoView({behavior:'smooth',block:'start'});});}
 async function report(level:Report['level']){setPosting(true);setMessage('');try{const r=await fetch('/api/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({spaceId:reportSpace,level})});const body=await r.json() as {error?:string};if(!r.ok)throw Error(body.error||'Could not save your report.');setMessage('Thanks — your observation is saved and visible for 15 minutes.');setNow(Date.now());await refresh();}catch(e){setMessage(e instanceof Error?e.message:'Could not save your report.');}finally{setPosting(false);}}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'configure_gap_plan',description:'Update the visible campus gap plan. Does not reserve seating.',inputSchema:{type:'object',properties:{from:{type:'string'},to:{type:'string'},date:{type:'string'},start:{type:'string'},end:{type:'string'},intent:{type:'string',enum:['study','quiet','group','break','eat']}},required:['from','to','date','start','end','intent'],additionalProperties:false},execute(input:unknown){if(!input||typeof input!=='object')throw Error('Expected plan inputs');const p={...bootstrapPlan,...input} as Plan;const r=recommend(p,data);if(r.error)throw Error(r.error);setDraft(p);setPlan(p);setSelected('');setBackup('');setError('');return {status:'configured',places:r.results.map(x=>({name:x.name,usableMinutes:x.usable,leaveBy:clock(x.leave)}))};}},{signal:lifecycle.signal})).catch(()=>{});return ()=>lifecycle.abort();},[]);
 const backupOption=result.results.find(s=>s.id===backup);
 const fallbackPlan=active&&backupOption?{...plan,from:active.buildingId,start:timeValue(Math.max(liveTime.date===plan.date?liveTime.minute:0,active.arrival))}:null;
 const fallback=fallbackPlan?recommend(fallbackPlan,data,reports,now).results.find(s=>s.id===backup):null;
 function switchBackup(){if(!fallback||!fallbackPlan)return;setDraft(fallbackPlan);setPlan(fallbackPlan);setSelected(fallback.id);setBackup('');setAiResult(null);setRouteMessage('Plan B selected with updated walking time.');}
 const fromBuilding=buildings.find(b=>b.id===plan.from),toBuilding=buildings.find(b=>b.id===plan.to);
 const mapsUrl=active&&fromBuilding&&toBuilding?`https://www.google.com/maps/dir/?api=1&origin=${fromBuilding.lat},${fromBuilding.lon}&destination=${toBuilding.lat},${toBuilding.lon}${active.buildingId!==plan.from&&active.buildingId!==plan.to?`&waypoints=${active.building.lat},${active.building.lon}`:''}&travelmode=walking`:'';
 return <><header className="topbar"><a className="wordmark" href="/"><span className="logo">h<span>g</span></span>hokiegap</a><span className="campus-label"><MapPin size={15}/> Virginia Tech · engineering cluster</span><a href="#data-notes" className="source-link">About the data <ArrowUpRight size={15}/></a></header>
 <main><section className="intro"><div><p className="eyebrow">BETWEEN CLASSES, ON YOUR TERMS</p><h1>A little gap. A good place.</h1><p>Find somewhere to settle in, with time to make your next class.</p></div><div className="gap-number"><strong>{minutes(plan.end)-minutes(plan.start)}</strong><span>minutes to work with</span></div></section>
 <section className="ai-planner"><h2>Ask HokieGap</h2><p>Describe what you need. Your buildings and times below set the boundaries.</p><label>Your request<Input value={aiRequest} onChange={e=>setAiRequest(e.target.value)} maxLength={1000} placeholder="I need somewhere quiet with less than 8 minutes of walking"/></label><Button onClick={()=>void askAgent()} disabled={!aiEnabled||aiBusy||!aiRequest.trim()||!!validate(draft,buildings)}>{aiBusy?'Finding a plan…':'Plan with AI'}</Button><p className="caption">{aiEnabled?'Your request and gap details are sent to Gemini. Avoid private information.':'AI setup is pending. Use the manual planner below.'}</p>{aiError&&<p role="alert">{aiError}</p>}{aiResult&&<div role="status"><p>{aiResult.explanation}</p><details><summary>How this recommendation was made</summary><ol>{aiResult.trace.map((x:string)=><li key={x}>{x}</li>)}</ol><p>{aiResult.source} · {aiResult.model}</p></details></div>}</section><div className="workspace"><aside className="planner"><div className="panel-title"><span className="step">01</span><h2>Your gap</h2></div><form onSubmit={e=>{e.preventDefault();apply(draft);}}>
 <label>Starting from<NativeSelect value={draft.from} onChange={e=>setDraft({...draft,from:e.target.value})}>{buildings.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</NativeSelect></label>
 <label>Next class in<NativeSelect value={draft.to} onChange={e=>setDraft({...draft,to:e.target.value})}>{buildings.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</NativeSelect></label>
 <label>Date<Input type="date" required value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label>
 <div className="two-fields"><label>Free from<Input type="time" required value={draft.start} onChange={e=>setDraft({...draft,start:e.target.value})}/></label><label>Next class<Input type="time" required value={draft.end} onChange={e=>setDraft({...draft,end:e.target.value})}/></label></div>
 <label>I want to<NativeSelect value={draft.intent} onChange={e=>setDraft({...draft,intent:e.target.value})}><option value="study">Get some work done</option><option value="quiet">Find a quieter spot</option><option value="group">Work with friends</option><option value="eat">Get something to eat</option><option value="break">Take a break</option></NativeSelect></label>
 <details className="preferences"><summary>More preferences</summary><div className="two-fields"><label>Maximum walk each way<NativeSelect value={draft.maxWalk} onChange={e=>setDraft({...draft,maxWalk:+e.target.value})}>{[3,5,8,12,15,20].map(n=><option key={n} value={n}>{n} min</option>)}</NativeSelect></label><label>Arrive early<NativeSelect value={draft.buffer} onChange={e=>setDraft({...draft,buffer:+e.target.value})}>{[0,5,10,15].map(n=><option key={n} value={n}>{n} min</option>)}</NativeSelect></label></div>
 <label>Opening hours<NativeSelect value={draft.confirmedOnly?'confirmed':'all'} onChange={e=>setDraft({...draft,confirmedOnly:e.target.value==='confirmed'})}><option value="all">Include unknown hours</option><option value="confirmed">Only confirmed hours</option></NativeSelect></label><p className="caption">Uses published schedules, not a live door check. Places with unknown hours are hidden when this filter is on.</p></details>
 {dirty&&<p className="notice">Inputs changed. Update results before using the route.</p>}{error&&<p role="alert" className="error">{error}</p>}<Button type="submit" className="primary-btn">{dirty?'Update results':'Find my spot'} <ArrowRight size={18}/></Button></form><button className="text-button" onClick={()=>{const p=currentPlan(draft);setDraft(p);apply(p);}}>Start now · one-hour gap</button><p className="caption">Eastern Time. Late-night gaps end at 11:59 PM; overnight planning is not supported.</p>
 <details className="preferences"><summary>Saved gaps</summary><p className="caption">Saved on this device. Choose a saved gap, then check the date.</p><label>Gap name<Input value={gapName} onChange={e=>setGapName(e.target.value)} placeholder="MWF morning" maxLength={60}/></label><Button variant="outline" disabled={!gapName.trim()||!!validate(draft,buildings)} onClick={saveGap}>Save this gap</Button>{savedGaps.map(g=><div className="saved-gap" key={g.name}><button onClick={()=>{const p={...g.plan,date:liveTime.date};setDraft(p);apply(p);}}>{g.name}</button><button aria-label={`Remove ${g.name}`} onClick={()=>setSavedGaps(v=>v.filter(x=>x.name!==g.name))}>Remove</button></div>)}</details></aside>
 <section className="results"><div className="results-heading"><div className="panel-title"><span className="step">02</span><h2>Places that fit</h2></div><span>{result.results.length} {result.results.length===1?"option":"options"}</span></div><p className="results-sub">Compared by available time, class-change activity and recent seat reports.</p>
 {departed&&<p className="notice">Your planned start is in the past. Use “Start now” or update the time.</p>}{dirty&&<p className="notice">Showing your previous search until results are updated.</p>}<div className="report-strip"><span className="status-dot"/>{reportStatus}<Button variant="ghost" size="icon-sm" aria-label="Refresh seating reports" onClick={()=>void refresh()}><RefreshCw size={14}/></Button></div>
 {result.results.length===0&&<div className="empty"><h3>{plan.confirmedOnly?'No places with confirmed hours fit these constraints.':'No places fit these constraints.'}</h3>{plan.confirmedOnly&&<Button onClick={()=>{const p={...plan,confirmedOnly:false};setDraft(p);apply(p);}}>Include unknown hours</Button>}<p>Try a longer gap, a larger walking limit or include unverified hours. We require at least 15 usable minutes.</p></div>}
 {(showAll?result.results:result.results.slice(0,3)).map((s,i)=><article className={`spot-card ${active?.id===s.id?'selected':''}`} key={s.id}><div className="card-kicker"><span>{i===0?'BEST FIT':`OPTION ${String(i+1).padStart(2,'0')}`}</span><span className={`surge ${s.crowd.score>=30?'high':''}`}>{s.crowd.available?`Class activity: ${s.crowd.label}`:s.crowd.label}</span></div><button className="spot-title" onClick={()=>showPlan(s.id,s.name)} aria-expanded={active?.id===s.id}>{s.name}<ArrowUpRight size={20}/></button><p className="location">{s.location}</p><div className="metrics"><strong>{s.usable}<small> minutes available</small></strong><span><Footprints size={16}/>{s.walkIn}-minute walk</span><span><Clock size={15}/>Leave for class by {clock(s.leave)}</span></div><div className="card-bottom"><span className={s.latest?'seat-report':'unknown'}>{s.latest?reportLabels[s.latest.level]+' · student report':'No recent seating reports'}</span><span>{s.open?'Open per published hours':'Opening hours not verified'}</span></div><div className="card-actions"><Button variant="ghost" onClick={()=>showPlan(s.id,s.name)}>{active?.id===s.id?'Route shown':'View route'} <ArrowRight size={15}/></Button><Button variant="ghost" disabled={active?.id===s.id} onClick={()=>setBackup(backup===s.id?'':s.id)}>{backup===s.id?'Remove Plan B':'Add as Plan B'}</Button><Button variant="ghost" aria-pressed={favorites.includes(s.id)} onClick={()=>setFavorites(v=>v.includes(s.id)?v.filter(x=>x!==s.id):[...v,s.id])}>{favorites.includes(s.id)?'★ Saved':'☆ Save place'}</Button></div></article>)}{result.results.length>3&&<Button variant="outline" onClick={()=>setShowAll(!showAll)}>{showAll?'Show fewer places':`Show ${result.results.length-3} more places`}</Button>}
 </section>
 <aside id="route-plan" className="detail-panel" tabIndex={-1}>{active&&<><div className="panel-title"><span className="step">03</span><h2>Your route & timing</h2></div><p className="sr-only" aria-live="polite">{routeMessage}</p>
 <h3 className="detail-name">{active.name}</h3><ol className="timeline"><li><span>{clock(minutes(plan.start))}</span><div>{plan.from===active.buildingId?'Stay in':'Leave'} {fromBuilding?.name}<small>About {active.walkIn} min to your spot</small></div></li><li className="main-stop"><span>{clock(active.arrival)}</span><div>Settle in for {active.usable} minutes<small>{plan.intent==='eat'?'Includes ordering and eating. Queue times and venue hours are not verified.':plan.intent==='break'?'Time to take a breather.':'A pocket of time to make progress.'}</small></div></li><li><span>{clock(active.leave)}</span><div>Head to {toBuilding?.name}<small>About {active.walkOut} min walking · {plan.buffer} min buffer</small></div></li><li><span>{clock(minutes(plan.end))}</span><div>Next class starts</div></li></ol>
 {mapsUrl&&<a className="map-link" href={mapsUrl} target="_blank" rel="noreferrer"><Navigation size={17}/><span>Open walking directions<small>{fromBuilding?.name} → {active.building.name} → {toBuilding?.name} · leave {clock(minutes(plan.start))}</small></span><ArrowUpRight size={16}/></a>}
 <div className="forecast"><div><h3>Expected class-change activity</h3><span className="small-tag">ESTIMATE</span></div><p>{active.crowd.available?`${active.crowd.label} activity`:active.crowd.label} around {clock(active.crowd.time)}</p>{active.crowd.available&&<div className="bars">{Array.from({length:7},(_,i)=>{const t=Math.round(active.arrival+i*(active.leave-active.arrival)/6),c=forecast(active.buildingId,plan.date,t,data);return <div key={i} title={`${clock(t)}: ${c.label}`}><span style={{height:`${Math.max(6,Math.min(58,c.score))}px`,background:c.score>=30?'#ce6a39':c.score>=10?'#d8ad72':'#9aab90'}}/><small>{i%3===0?clock(t).replace(' AM','').replace(' PM',''):''}</small></div>;})}</div>}<p className="caption">Estimated activity from classes, not total crowds. Low activity does not mean seats are available. Forecast coverage: Sept 19–25, 2026.</p>{active.crowd.events.map(e=><p className="event" key={e.room+e.end}>{e.course} ends {clock(e.end)} · {e.room}<small>Section capacity {e.capacity}; enrollment unknown</small></p>)}</div>
 {backupOption&&backup!==active.id&&<div className="backup"><div><strong>Plan B: {backupOption.name}</strong><p>{fallback?`${fallback.walkIn}-minute walk from ${active.name}; ${fallback.usable} minutes available. Leave by ${clock(fallback.leave)}.`:'This backup no longer fits from your selected spot.'}</p><Button disabled={!fallback||dirty} onClick={switchBackup}>I’m here · switch to Plan B</Button><button className="text-button" onClick={()=>setBackup('')}>Remove</button></div></div>}<Button variant="outline" onClick={()=>{setReportSpace(active.id);document.getElementById('seat-reports')?.scrollIntoView({behavior:'smooth'});}}>Report seats at this place</Button>
 <details className="place-details"><summary>What we know about this spot</summary><p>{active.note}</p><p>{active.verification}. Seat count and current outlet availability are unknown.</p><a href={active.source} target="_blank" rel="noreferrer">Read the place source <ArrowUpRight size={14}/></a><p className="caption">Walks use building coordinates, a 35% detour allowance, 70 m/min pace and 2 minutes indoors. Actual routes, stairs and accessible entrances may take longer.</p></details></>}</aside></div>
 <section id="seat-reports" className="community"><div><p className="eyebrow">HELP THE NEXT STUDENT</p><h2>Here right now? Share the seat situation.</h2><p>Report only what you can see at the selected spot. Reports are shown for 15 minutes. Anonymous observations may be kept to improve the forecast.</p><p className="caption">Reports describe now, even when your plan is for another day. They influence a plan only if still fresh at arrival.</p></div><div className="report-controls"><label>Where are you?<NativeSelect value={reportSpace} onChange={e=>setReportSpace(e.target.value)}>{spaces.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</NativeSelect></label><div className="report-buttons">{(['plenty','few','none'] as const).map(level=><Button key={level} variant="outline" disabled={posting} onClick={()=>void report(level)}>{reportLabels[level]}</Button>)}</div><p role="status">{message}</p>{freshReports(reports,reportSpace,now)[0]&&<p className="caption">Latest observation: {reportLabels[freshReports(reports,reportSpace,now)[0].level]} · {Math.floor((now-freshReports(reports,reportSpace,now)[0].createdAt)/60000)} min ago</p>}</div></section>
 <details id="data-notes" className="data-notes"><summary><Info size={17}/> Data, coverage & limitations</summary><div className="notes-grid"><div><h3>Real sources, defined coverage</h3><p>{buildings.length} building coordinates from VT GIS and {spaces.length} destinations from university or architect descriptions. Bishop-Favrao is currently a route endpoint until a suitable public space is verified.</p><p>The Sept 19 snapshot includes {classes.length} meetings from 14 subjects. It uses section capacity rather than enrollment and does not collect private rosters.</p><a href="https://selfservice.banner.vt.edu/ssb/HZSKVTSC.P_DispRequest" target="_blank" rel="noreferrer">VT public timetable ↗</a></div><div><h3>Forecast model</h3><p>The current class-change forecast covers Sept 19–25, 2026. It estimates how nearby class starts and endings affect demand; observations will be used to calibrate and extend it.</p><p>Library hours are a dated calendar snapshot. Other opening hours are unknown. Schedules and access can change.</p><a href="https://lib.vt.edu/about-us/hours.html" target="_blank" rel="noreferrer">Check current library hours ↗</a></div><div><h3>Live reports</h3><p>Seating observations are stored on the service and influence recommendations for 15 minutes. They are not reservations or guarantees.</p><p>The optional AI planner shows the actual data source used for each request. Class-change activity is an uncalibrated scheduling heuristic. HokieGap is an independent student project.</p></div></div></details>
 <footer><span className="wordmark">hokiegap</span><span>A better use of the time between.</span></footer></main></>;
}
